aiolifx/aiolifx.py

The periodic timeout was hardcoded, making the discovery_interval parameter useless.

Use discovery_interval parameter

---

aiolifx/aiolifx.py

This plugs a file descriptor leak discovered by @mihalski in home-assistant/home-assistant#6985
To reproduce:
1. Start the example cli program
2. Power off a bulb
3. Send a command to that bulb, so that it unregisters
4. Power on the bulb and let it register
5. Observe (for example with ```lsof```) that two UDP sockets now exist for that bulb
What do you think?

Close transport on unregister

---

aiolifx/msgtypes.py

The `b` prefix seems to have been missed in this single place. The problem was reported in home-assistant/home-assistant#7224 but I do not have a LIFX Z to validate.

Use bytes for payload concatenation

---

aiolifx/aiolifx.py

A device can unregister at any time and clients have to do a lot of
bookkeeping to avoid warnings because they sent to a device that just
disappeared.
This change allows clients to send messages into the void left by `unregister`.
It is a bit naive as the resend/unregister logic is still invoked for each
unsent message but no harm should be caused by this extra work.

Test for transport before sending to it

---

aiolifx/aiolifx.py
aiolifx/aiolifx34.py

This field is documented to always be zero. Yet, so far it wasn't. But now it
is. Better just leave it alone.

Ignore response.origin

---

aiolifx/aiolifx.py

I wanted to experiment with retries and timeouts because I have some connectivity problems. However, I learned that I could only do that by modifying the aiolifx source.
So I propose this change to make those settings configurable for clients.
The duplicated broadcasts at startup are removed because I don't think it is needed and it interfered with using `timeout` for this new purpose. I can add that functionality back in if you prefer.
Also, I made the `fire_and_forget` throttle always active since I believe the "20 messages per second" limit it meant to say something about processing power, not buffer size.
Finally, I removed an unused `bcast_count` variable.

Add timeout values to devices

---

aiolifx/aiolifx.py

I have spent a lot of time experimenting with retries/timeouts/discovery_interval and I have come to the conclusion that UDP (on LIFX in particular) is so unreliable that it is overkill to exclude a light just because it misses a single message. Many times I see a light unregister and then reply to messages just two seconds later.
So I have made this PR that changes the API somewhat, giving clients more control:
* Callbacks are now called with a None response if we give up waiting for the response.
* It is possible to send/receive messages even after a light has unregistered.
Now `unregister` is just an event that signals bad connectivity. Clients can ignore or use it as they like. They are free to stop all communication like before or they can continue communication and hope that the …

Stay connected

---

aiolifx/aiolifx.py

Hello again.
In investigating connectivity issues, I tried setting up a separate VLAN (and SSID) for LIFX bulbs. I was unable to get aiolifx to discover bulbs until I manually provided the broadcast address for the new VLAN subnet (e.g. 10.0.2.255). This was even though I set the local_addr to be on the right subnet when creating my LifxDiscovery endpoint.
This is a simple change to help in this situation. It could be possible to find the broadcast address automatically but I know of no portable way. By the way, I was testing this on macOS.
Also, if the beta has been working for you (it has for me), can you do a 0.5.0 final release? It would look a bit nicer in my requirement list :)

Make broadcast_ip configurable

---

aiolifx/aiolifx.py
aiolifx/aiolifx34.py

The `unregister` callback was already skipped if a message was dropped within `DEFAULT_TIMEOUT` of a received message. This PR makes the duration configurable.
This change makes sense to me now that the client is free to keep using the aiolifx Light even after it has unregistered. It specifies a grace period where the client will keep trying (for example when the user presses a physical button again after a few seconds).
I have experimented with this value and setting it to 60 seconds removes the intermittent dropouts that I was seeing. It is of course still possible to send a command that is not executed by the bulb. However, the risk is much smaller when it is only the bulb that goes unresponsive, not aiolifx.
(I am also updating aiolifx34.py in this PR as it seems that the …

Unregister timeout

---

aiolifx/message.py

It was reported that the Home Assistant LIFX integration is broken with the upcoming Gen2 firmware version 1.22: home-assistant/home-assistant#8284. This firmware is so far only available from LIFX support so it's not a big issue yet but in a few days it will be.
I have found out that the problem is that the message size is calculated wrongly and apparently the LIFX firmware has started to check that.
CC: @mclarkk because I think this bug was inherited from lifxlan

Fix message size calculation

---

aiolifx/aiolifx.py
aiolifx/aiolifx34.py

The end_index is the last zone to include, not the first zone to exclude.
This error caused LIFX Z to send an extra response message.

Fix off-by-one error in get_color_zones

---

examples/lifx-cli.py

This matches how it is used elsewhere (and is easier to understand).

Reword Value as Brightness

---

aiolifx/aiolifx.py

I have been fighting an issue where the `Device` method `datagram_received` stopped being called. It turns out that some firmwares (tested with LIFX Mini Color v3.40) combined with uvloop on Linux can cause this behavior, for example due to a power cycle. The event loop simply stops polling the socket when an error is detected.
This PR changes the reconnect logic so the socket is always recreated, even if its parameters are identical to the unregistered socket. This makes the event loop start polling for data once again.

Always reconnect when rediscovering a light

---

README.md
aiolifx/aiolifx.py
examples/lifx-cli.py

This moves a little boilerplate into the library.
I think it is quite a good sign that the example program gets shorter and avoids two constants.
A few typos/whitespace have also been fixed.

Add discovery start method to create datagram endpoint

---

aiolifx/__init__.py
aiolifx/aiolifx.py
examples/lifx-cli.py
setup.py

When a machine has multiple network interfaces, I need a way to find the one where LIFX bulbs are available.
This new class does that by starting discovery on all interfaces and returning the local address(es) of the ones that receive a response within one second.

Add LifxScan class for finding networks with bulbs

---

aiolifx/aiolifx.py

I am not sure that 1 second is always the best timeout value so I thought, why not make it possible for the client to select the timeout.

Make scan timeout configurable

---

aiolifx/aiolifx.py

I am starting to use `cleanup()` and have noticed that exceptions can appear when the cleanup happens during message sending and `self.transport` becomes `None`.

Stop message sending after cleanup

---

aiolifx/aiolifx.py

Apparently `ifaddr` will not find any network adapters in some rare configurations.
This PR improves the error handling in that case, avoiding [this exception](https://community.home-assistant.io/t/lifx-integration-implementation-issues/82436):
```text
2018-12-02 15:32:21 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform lifx
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
SLOW_SETUP_MAX_WAIT, loop=hass.loop)
File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
return fut.result()
File "/usr/local/lib/python3.6/site-packages/homeassistant/components/light/lifx.py", line 151, in async_setup_entry
lifx_ip_addresses = await …
```

Avoid LifxScan exception when no adapters are found

---

aiolifx/message.py
aiolifx/msgtypes.py

I have profiled (py-spy) Home Assistant and found that aiolifx is taking up a lot of my CPU usage. I went ahead and optimized the hot paths in my setup:
* Construct the message header with `struct`, not `bitstring` (much faster)
* Only generate a packed message when accessed (so usually not for received messages)
* Simplify two methods working on bytes
With these changes, aiolifx all but disappears from the flame graph.

Optimize message generation

---

aiolifx/aiolifx.py

Hello, thanks for making the release yesterday. A new issue has unfortunately surfaced.
We have a problem identifying the firmware version because it is converted to a `float`. This means that a current version like `3.70` is identical to an old version `3.7` and that confuses the update logic.
I also noticed that the minor version is really 16 bits, not 8 bits. AFAIK, this has not been an issue because minor versions have not reached 256 yet. https://lan.developer.lifx.com/docs/information-messages#statewififirmware---packet-19
This PR fixes both issues. It is a breaking change since the type of `self.host_firmware_version` changes from `float` to `str`.

Fix host_firmware_version issues

---

aiolifx/__main__.py
aiolifx/aiolifx.py
aiolifx/msgtypes.py
aiolifx/unpack.py
examples/lifx-cli.py

Reference: https://lan.developer.lifx.com/docs/hev-light-control
I'm mainly interested in using this with Home Assistant, there's some people asking about it over here: https://community.home-assistant.io/t/lifx-clean/309219
I added code for it in the example script:
```
% python examples/lifx-cli.py
Hit "Enter" to start
Use Ctrl-C to quit
Select Bulb:
(REDACTED)
Select Function for (REDACTED):
[1]	Power (0 or 1)
[2]	White (Brigthness Temperature)
[3]	Colour (Hue Saturation Brightness)
[4]	Info
[5]	Firmware
[6]	Wifi
[7]	Uptime
[8]	Pulse
[9]	HEV cycle (duration, or -1 to stop)
[10]	HEV configuration (indication, duration)
[0]	Back to bulb selection
Your choice: 9
Getting current HEV state
HEV: duration=7200, remaining=0, last_power=True
HEV result: SUCCESS
Your choice: 9 0
Running HEV …
```

Adds support for HEV Light Control (LIFX Clean)

---

aiolifx/aiolifx.py
setup.py

This uses the `feature_map` to ensure the requests only go to devices with the HEV capability.

Only send HEV packets to devices with that feature

---

aiolifx/aiolifx.py
aiolifx/msgtypes.py
examples/lifx-cli.py

This allows you to programmatically restart a device. I added an
option to `lifx-cli.py` for this as well. Check the uptime value
after the reboot to confirm it worked.

Add a SetReboot message type and set_reboot method

---

aiolifx/aiolifx.py
aiolifx/msgtypes.py
aiolifx/unpack.py
examples/lifx-cli.py

This enables control of the Move firmware effect on linear multizone LIFX devices, including LIFX Z, Lightstrip and Beam. More detail in the `set_multizone_effect()` docstring.
The example CLI is also tweaked to only should HEV and multizone options to devices that are compatible with those options.

Add get_multizone_effect() and set_multizone_effect()

---

aiolifx/__main__.py
aiolifx/aiolifx.py
examples/lifx-cli.py

This aligns the functionality of `examples/lifx-cli.py` with `aiolifx/__main__.py` so that the provide the same example functionality. I also ran `black` over the sources to ensure the post-merge action is successful.
Resolves feedback from the review of #59.

Add multizone and reboot examples to the aiolifx cli util

---

aiolifx/aiolifx.py
aiolifx/msgtypes.py
aiolifx/unpack.py

I didn't add anything to `__main__.py` or `examples/lifx-cli.py` as there is no example for the existing `set_color_zones` method.  
However, I did create a test script that scans for multizone devices and sets a random color on each of its zones using `set_extended_color_zones` every 2 seconds which you can find here: https://gist.github.com/Djelibeybi/3d7990e861e6f1037f5101b61215db20
Just replace "INSERT MAC ADDRESS HERE" with the MAC address of a multizone device and run. Hopefully successfully. :)

Add support for extended_multizone messages

---

aiolifx/aiolifx.py
aiolifx/msgtypes.py
aiolifx/unpack.py

These methods work very much like the multizone effects to start/stop either the `morph` or `flame` effect on LIFX Tile or Candle devices. The device must have the "matrix" feature for these methods to work. The `set_tile_effect()` method will use the Exciting theme for the `morph` effect if a `palette` is not provided.

Added support for Tile/Candle firmware effects

---

aiolifx/aiolifx.py
aiolifx/msgtypes.py
aiolifx/unpack.py
examples/lifx-cli.py
setup.py

Adds the three messages defined in the [LIFX Switch](https://lan.developer.lifx.com/docs/the-lifx-switch) docs:
- `GetRPower`
- `SetRPower`
- `StateRPower`
Screenshot of it working on the CLI:
CLI usage is:
`11 <relay_number> <on|off>`. If you don't specify `on/off` it just tells you the status (of either all relays, or just the one if you've specified a `relay_number`)
Solves: https://github.com/frawau/aiolifx/issues/39

Add lifx switch support

---

aiolifx/__main__.py
aiolifx/aiolifx.py
aiolifx/message.py
aiolifx/msgtypes.py
aiolifx/unpack.py
examples/lifx-cli.py
setup.py

`asyncio.wait_for` creates another tasks which leads to some race conditions in cancelation and a performance hit
cpython 3.12 will change the underlying implementation of `asyncio.wait_for` to use `asyncio.wait` but that is still a long way off for many people:
https://github.com/python/cpython/pull/98518

Switch to using async_timeout/asyncio.timeout

---

.gitignore
README.md
aiolifx/__main__.py
setup.py

I'd like to update the CLI to be more user-friendly and interactive. I think originally the CLI was good for testing and debugging when there weren't too many LIFX products, but given there are now quite a few I thought a few areas could use improvements:
- Code is a bit hard to read when we have branching options to support different lifx products/features. E.g. options 9 and 10 were either `hev` or multizone effects
- When setting values, the user needs to know **what** to input, and in what order to put arguments. E.g. for `set_color` they need to know `hue` is first, and accepts 0 through 360; `saturation` is next and accepts 0 through 100 etc.
- When unpacking user inputs in the code, we need to remember that `lov[1]` is `hue`, `lov[2]` is `saturation` etc.
- We also need to validate …

Upgrade `__main__.py` CLI to be more interactive

---

aiolifx/aiolifx.py

dir has to enumerate the entire object where
as getattr only does a lookup.
Noticed this in a profile provided by a user
tested with a lifx beam
with dir
without dir

Replace expensive dir call with getattr

---

aiolifx/__main__.py
aiolifx/aiolifx.py
aiolifx/msgtypes.py
aiolifx/unpack.py

This includes the updated protocol changes for the `SKY` effect only available on LIFX Ceiling devices running firmware 4.4 or higher. 
I've tested this on my LIFX Tiles, Spot, Path and Ceiling devices but would welcome others with matrix devices to test it too.

feat: add support for controlling matrix firmware effects

---

aiolifx/aiolifx.py
aiolifx/msgtypes.py
aiolifx/unpack.py

This adds most (but not all) the Tile messages which are required for querying and controlling LIFX Tile, Candle, Path, Spot and Ceiling devices. This PR includes the fix in #83 so you can drop that if you merge this one.

Add methods for querying and changing LIFX matrix devices
